version: 2

models:
  - name: stg_womenontour
    columns:
      - name: artist
        tests:
          - not_null
      - name: actual_gross
        tests:
          - not_null
      - name: tour_title
        tests:
          - unique
          - not_null
      - name: year_start
        tests:
          - not_null